### ISSUE TITLE
Bug? Network stealing items before any chests are made..

### ISSUE THREAD

**Issue by Neb2566** [year6b7a/item-network-factorio-mod#15]
I was going to do a playtrough where I needed space science to craft the chests to make them endgame, noticed at the start of the playtrough that the network took items from my trash slot before I even made any chests. Not sure if this was inteded or not but figured I would make you aware of this if not.

**Comment by year6b7a** [comment]
Nice idea to make these chests require space science!

The "trash before network chests are unlocked" behavior is intentional but probably not desired for that play-style. I've been planning on adding some settings or configuration options to the mod and this seems like a great candidate.

At the very least I'll add a flag to disable network trash until the player builds their first network chest.

I can also add a runtime setting so the player can toggle network trashing on/off as desired.

At the very least, players can now use "Ctrl+Shift+N" to view the contents of the network and it might be nice to just let players pick items out of the network.

What do you think?

**Comment by year6b7a** [comment]
Implemented in d19f7532e5ba616fadde34e679cc404de7242d5f with these changes:
- Item network logistics are disabled until a network chest has been placed
- Players can individually choose to item network logistics depending on play style.

![image](https://github.com/year6b7a/item-network-factorio-mod/assets/135451123/cbd82b4b-2379-431b-9eb8-1ec1a8b21797)

**Comment by Neb2566** [comment]
Moning, "At the very least, players can now use "Ctrl+Shift+N" to view the contents of the network and it might be nice to just let players pick items out of the network." Sounds nice. Awesome job with the mod :) Going to update the mod now and start testing the changes done so far :)

Edit:
The enable option for logistics is perfect :)
