### ISSUE TITLE
Can't place network tank on Space exploration space tiles

### ISSUE THREAD

**Issue by SwornGamer** [year6b7a/item-network-factorio-mod#24]
I've been enjoying this mod for my playthrough of SE + K2 however when you added the network tanks I thought to change a bunch of automations however you can't place network tanks on space platforms, spaceships, and asteroids. Which is unfortunate but maybe you can fix that.

**Comment by year6b7a** [comment]
Thanks for reporting this bug. I haven't played SE myself but I'm aware that the mod prevents placing certain items in space to make logistics more challenging.

Fixed in 6277583712628c3b61eba3122d1eb86ad4b79f21 by allowing Network Tanks and Loaders to be placed in space. Will release in the next version.

In general, the Item Network mod is intended more for modpacks that add resource management challenges (Bob's and Angels, Pyanodons, etc.) and less for logistic challenges like SE. I'm fine with adding this change since it's pretty straightforward and sticks with the theme of this mod being cheaty but probably won't support more complicated integrations with SE.
