### ISSUE TITLE
Add bottlenecks to Network View

### ISSUE THREAD

**Issue by year6b7a** [year6b7a/item-network-factorio-mod#26]
It should be possible to detect bottlenecks in the network when a request for items is not satisfied. It would be cool to explore adding this info to the network view to help plan which bottlenecks to fix next.

**Comment by bengardner** [comment]
I thought about this a little bit.  Since we only scan a subset of the chests/tanks in a tick, it would be tricky to know when we got through the whole list.
I think there are two different approaches that would work. Both involve a table added to globals.mod.

1) Record the tick count when an item request was not satisfied. (key=item name, val=tick)
Update the tick count every time the item is wanted, but not available.
When displaying the bottlenecks, discard any with a tick count above a threshold (5 seconds?)

or

2) add the item name to a table (key=name, val=true) when a request is NOT satisfied, Remove when any request for that item is satisfied.

 
I think #1 would work better.

**Comment by year6b7a** [comment]
Yeah 1 makes sense. It could be a map from item_name -> tick. 5 seconds sounds reasonable and that's easy to test and tune.

**Comment by bengardner** [comment]
Pull request #43 has shortage tracking for items and fluids.

**Comment by year6b7a** [comment]
Thanks for the contribution! What do you think about these changes?

1. Move all missing items and fluids into a new "tab" on the Network View page called "Missing".
2. Somehow track the quantity of missing items, maybe the number of requested items that weren't fulfilled in the last.

**Comment by bengardner** [comment]
Both of those changes sound good.

The quantity would have to be tracked using a more complicated structure.
Right now, we have `missing[item_name] = tick`.

We'd have to track each source tank/chest. Perhaps something like:
`missing[item_name][unit_number] = { tick, count }`

Then the `filter` function would collect the missing items into a structure like:
`missing[item_name] = count`

**Comment by bengardner** [comment]
I updated #43.  I think this can be closed when that is merged.

**Comment by bengardner** [comment]
#43 needed a rebase. I accidentally closed it and then created pull request #47 after rebasing.

**Comment by year6b7a** [comment]
Got it, thanks for rebasing. I'll take a look and try to get it merged today.

**Comment by year6b7a** [comment]
Closing now that #47 has merged. Thanks!
