### ISSUE TITLE
enhancement: Directly supply missing items to logistic network

### ISSUE THREAD

**Issue by bengardner** [year6b7a/item-network-factorio-mod#45]
The "alerts" provide an indirect way to detect that materials are missing from a logistic network.

I read the player alerts and parse out the entity for the missing resources and then directly insert() the missing item into the logistic network.
I track which alerts/entities have been serviced to not send multiple items for one alert.
It works great.
I can paste a blueprint that contains items in the item network, but not the local logistic network and the items are transferred over and the robots place them.
I'm pretty sure this requires available storage in the logistic network.

I haven't tested in multi-player. I assume that all players will see the same alert and that the entity will have the same unit_number for all players, 
It needs a little more cleanup. For example, I need to make sure a construction robot is available before pushing the item.
I also haven't figured out the proper "force" to use, but then item-network doesn't support multiple forces either,

I'll try to extract and post the changes in the next day or so.

**Comment by bengardner** [comment]
Pull request #46 implements this.

**Comment by year6b7a** [comment]
I gave #46 a try and it's really nice to use. I have a few implementation questions that I'll leave in the pr and it looks like there are some changes that you want to make now that #47 has merged.

**Comment by year6b7a** [comment]
This implementation in #46 works well. I tested this with multiple roboports and with ghosts outside bounds and everything seems to work well.

The only strange behavior I could find is that entities outside the logistic area but inside the construction area aren't supplied because [`find_logistic_network_by_position`](https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.find_logistic_network_by_position) finds the current logistic network and not the current construction network. I couldn't find an easy way to improve this, but if anyone has other ideas they're welcome to give it a try.

![Screenshot from 2023-08-11 20-22-55](https://github.com/year6b7a/item-network-factorio-mod/assets/135451123/5e9cec0e-3d5e-43a7-8b62-254c5aafbe0c)

Other than that, this is a great addition to the mod. Thanks!

**Comment by bengardner** [comment]
#56 uses the correct function: `find_logistic_networks_by_construction_area()`
I created ticket #55 before realizing this wasn't closed.

**Comment by year6b7a** [comment]
Sounds good. I'll close out these issues since it seems like they're done.
